base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('',views.base,name='base'),
  
]

catalog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.Index,name='index'),
    path('create_book/', views.BookCreate.as_view(),name='create_book'),
    path('book/<int:pk>/', views.BookDetail.as_view(),name='detail_book'),
    path('my_view/', views.myView,name='my_view'),
    path('signup_view/', views.SignUpView.as_view(),name='signup_view'),
    path('profile/', views.CheckOutBookByUserView.as_view(),name='profile'),

]

webapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('my_app1',include('my_app1.urls')),
    path('my_app2/',include('my_app2.urls')),
    path('car_rental/',include('car_rental.urls')),
    path('classroom/',include('classroom.urls')),
    path('catalog/',include('catalog.urls')),
    #path('',RedirectView.as_view()(url='catalog/')),
    path('accounts/',include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import  User

# Create your models here.
class Genre(models.Model):
    
    
     name = models.CharField(max_length=150)

     def  __str__(self):
          return self.name
     

class Language(models.Model):
    name =models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Book(models.Model):
    
    
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    summary = models.TextField(max_length=1000)
    isbn = models.CharField('ISBN',max_length=13,unique=True)
    language = models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)
    genre = models.ManyToManyField(Genre)


    def  __str__(self):
        return self.title 
    
    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})


class Author(models.Model):
    first_name =models.CharField(max_length=150)
    last_name =models.CharField(max_length=150)
    date_of_birth =models.DateTimeField(null=True,blank=True)
    genre = models.ManyToManyField(Genre)

    class Meta:
        ordering = ['last_name','first_name']
     
     

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})


    def __str__(self):
        return f"{self.last_name} , {self.first_name}"



import uuid

class Bookinstance(models.Model):

    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    book = models.ForeignKey('book',on_delete=models.RESTRICT,null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateTimeField(null=True,blank=True)
    borrower = models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
 

    LOAN_STATUS = (
        ('m','Maintenance'),
        ('o','On Loan'),
        ('a','Available'),
        ('r','Reserved')
    )


    status = models.CharField(max_length=200,choices=LOAN_STATUS,default='m',blank=True)



    class Meta:

        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'

catalog/views.py
from django.shortcuts import render
from .models import Book,Author,Bookinstance,Genre,Language
from django.views.generic import  CreateView,DetailView,ListView
from django.urls import reverse_lazy,reverse
from django.contrib.auth.decorators import  login_required
from django.contrib.auth.mixins import  LoginRequiredMixin
from django.contrib.auth.forms import  UserCreationForm


def Index(request):
    num_book = Book.objects.all().count()
    num_instances = Bookinstance.objects.all().count()
    #num_instances_avail =  Bookinstance.objects.filter(status_exact='a').count()

    context ={
        'num_book':num_book,
        'num_instances':num_instances,
        #'num_instances_avail':num_instances_avail
    }
    
    
    return render(request,'catalog/index.html',context=context)



class BookCreate(LoginRequiredMixin,CreateView):
    
    model = Book
    fields        = '__all__'
    success_url   =  reverse_lazy('detail_book')

    template_name = 'catalog/book_form.html'


class BookDetail(DetailView):
    model = Book
    template_name = 'catalog/detail_book.html'

@login_required
def myView(request):
    return render(request,'catalog/my_view.html')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'


class CheckOutBookByUserView(LoginRequiredMixin,ListView):

    model = Bookinstance
    template_name = 'catalog/profile.html'
    paginate_by   = 5

def  get_queryset(self):
    return Bookinstance.objects.filter(borrower=self.request.user).all

catalog/templates/catalog/book_form.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Create New Book</h1>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
        <script src="" async defer></script>
    </body>
</html>

catalog/templates/catalog/detail_book.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <h1>Detail Book</h1>
        {{book}}
        <script src="" async defer></script>
    </body>
</html>

catalog/templates/catalog/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
       <h1> My index Page</h1>
       <p> Total Number of book: {{num_book}}</p>
       <p>Number Available: {{num_instances_avail}}</p>
       {% if user.is_authenticated  %}
           <p>You Are logged In</p>
           <p>Welcome: {{user.get_username}}</p>
           <a href="{% url 'logout' %}?next={{request.path}}">Logout here</a>
       {% else %}
           <p>You are not logged In</p>
           <a href="{% url 'login' %}?next={{request.path}}"> Login here</a>
       {% endif %}
           
        <script src="" async defer></script>
    </body>
</html>

catalog/templates/catalog/my_view.html
<h1>Logged in user only!!</h1>

catalog/templates/catalog/profile.html
<h1>Welcome to yor profile</h1>
<h2>Here are your Books checked out:</h2>

{% for book in  bookinstance_list %}
    <p>{{book}}</p>

{% endfor %}

catalog/templates/catalog/signup.html
<h1>Register new user Here</hi>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="signup">
    </form>